# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubernetes'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'https://github.com/simplon-ThomasJulian/Brief_7/kubernetes'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

- task: CmdLine@2
  inputs:
    script: |
      cat /home/vsts/version/version.vote
      mkdir /home/vsts/version
      pwd
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      $NEWVERSION  = echo "$TESTVAR"|sed 's/^.//;s/.$//' > /home/vsts/ver/version
  name: 'TEST'
- bash: echo $(TEST.nameofthevariable)