# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubernetes'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo apt-get install jq'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl ''''https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags'''' | jq ''."results"[0]["name"]'''