apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp
  labels:
    app: voteapplb
spec:
  selector:
    matchLabels:
      app: voteapplb
  replicas: 1
  template:
    metadata:
      labels:
        app: voteapplb
    spec:
      containers:
      - name: voteapp
        image: simplonasa/azure_voting_app:v1.0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: TITLE
          value: "La pêche c'est bien?"
        - name: VOTE1VALUE
          value: "Oui"
        - name: VOTE2VALUE
          value: "Non"
        - name: STRESS_SECS
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: loadvoteapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: voteapplb